apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- configmap.yaml
- redis-claim0-persistentvolumeclaim.yaml
- redis-config.yaml
- redis-deployment.yaml
- redis-service.yaml
- secret.yaml
- web-claim0-persistentvolumeclaim.yaml
- web-deployment.yaml
- web-service.yaml
namespace: default
images:
- name: flask-redis-web
  newName: ansu0122/flask-redis-web
  newTag: "2.0"
