apiVersion: v1
kind: Service
metadata:
  name: flask-web-app
  labels:
    app: web-app
spec:
  ports:
    - name: "8000"
      port: 8000
      targetPort: 8000
  selector:
    app: web-app
  type: LoadBalancer
